version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: the-movie-app
    restart: unless-stopped
    container_name: the-movie-app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - app-network
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=pgsql
      - DB_HOST=the-movie-app-db
      - DB_PORT=5432
      - DB_DATABASE=the-movie-app
      - DB_USERNAME=postgres
      - DB_PASSWORD=password

  nginx:
    image: nginx:alpine
    container_name: the-movie-app-webserver
    restart: unless-stopped
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - app
    networks:
      - app-network
  db:
    image: postgres:latest
    restart: unless-stopped
    container_name: the-movie-app-db
    ports:
      - "5431:5432"
    volumes:
      - ./docker/dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: the-movie-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  dbdata: